### PR TITLE
Fable 1 support

### PR DESCRIPTION
**Pull request by forki**
subsumes #19

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Ok, I close #19 :+1: Things to do:

- Check if everything works removing the `Pojo` attribute
- Update Fable and libraries to 1.1.x (with Fable.Import.Browser split)
- Fix build script

**Comment by forki** [comment]
I'm working on the build

**Comment by forki** [comment]
image

@alfonsogarciacaro what now?

**Comment by forki** [comment]
@alfonsogarciacaro how is it supposed to work now?

**Comment by alfonsogarciacaro** [comment]
@forki I was just running Fable/Rollup and React Native in two different terminals:

```
#Terminal 1
dotnet fable npm-run build

#Terminal 2
react-native run-android
```

Remember to restore dependencies first :)

**Comment by forki** [comment]
run fableTool "--verbose --symbols PRODUCTION" ""

how would this look like?

**Comment by alfonsogarciacaro** [comment]
In Fable 1.0 it's the fable-loader which sends the symbols/defineconstants to the Fable daemon. The tricky part is Webpack won't accept custom arguments (I think). Right now what we usually do is to [detect if the `-p` argument has been passed to Webpack](https://github.com/fable-compiler/Fable/blob/964db2017e681104a082eb6d985725f611e6f68a/src/templates/simple/Content/webpack.config.js#L13-L14), and then [pass the appropriate define symbols](https://github.com/fable-compiler/Fable/blob/964db2017e681104a082eb6d985725f611e6f68a/src/templates/simple/Content/webpack.config.js#L40) for each case. But I'm not sure with Rollup, I'll check.

The `--verbose` argument can be passed normally: `dotnet fable npm-run build --verbose`. See: `dotnet fable --help` for details.

**Comment by forki** [comment]
good but I need to pass compiler directives as well

**Comment by alfonsogarciacaro** [comment]
Yes, you need to do it from the webpack.config.js (rollup.config.js in this case). It's not possible to pass compiler directives directly to Fable daemon because in theory the same daemon can be used to compile multiple projects with different configurations.

Anyways, don't worry, I'll do it later :+1:

**Comment by forki** [comment]
seems calling yarn install hangs for me

**Comment by forki** [comment]
yarn install v0.23.2

**Comment by alfonsogarciacaro** [comment]
Bad karma ;) Maybe try updating yarn or use npm 5 (`npm install -g npm` to update)

**Comment by alfonsogarciacaro** [comment]
I've made some changes in #19, maybe you can rebase/merge them to this PR?

- Update to Fable 1.1.3
- Remove `Pojo` attribute
- Detect if it's a production build in Rollup config (when you don't pass the `-w` argument) and in that case pass the `PRODUCTION` compiler directive to Fable). I've also changed the name of package.json script to `start` (watch/development) and `build` (production) to match other Fable templates :+1:

**Comment by alfonsogarciacaro** [comment]
Apparently the latest commits are not showing in #19 PR as it's closed, you need to check branch `fable-1-1` directly.

**Comment by forki** [comment]
image

**Comment by forki** [comment]
wtf?

**Comment by forki** [comment]
running `chcp 850` resolved it

**Comment by forki** [comment]
@alfonsogarciacaro now I'm lost:

image

**Comment by inosik** [comment]
@forki I think I ran into this once, when I tried to fix fsharp/FAKE#1461, at least I had the same stack trace.

Node.js seems to have a problem with the [`Console.OutputEncoding` change][assignment] we do in FAKE to prevent the Chinese characters bug on Mono.

  [assignment]: https://github.com/fsharp/FAKE/blob/15e1b741f4ae9fbaad640a65231dfcec28ce6ddd/src/app/FakeLib/ProcessHelper.fs#L28

Does the build script output any Unicode characters? I triggered this crash when printing the copyright character to the console.

**Comment by forki** [comment]
yes it seems related. sigh

**Comment by forki** [comment]
don't get it working. sigh

**Comment by forki** [comment]
(I think dotnet is also using wrong codepage)

**Comment by alfonsogarciacaro** [comment]
Maybe running Fable daemon (dotnet fable start) and npm script (npm run SCRIPT_NAME) separately can help? Fable tests do something similar (see runTestsJs function in Fable build script)

**Comment by alfonsogarciacaro** [comment]
Maybe running Fable daemon (dotnet fable start) and npm script (npm run SCRIPT_NAME) separately can help? Fable tests do something similar (see runTestsJs function in Fable build script)

**Comment by inosik** [comment]
If it's really a console encoding issue, then running the commands manually instead of starting them via FAKE should work.

**Comment by forki** [comment]
@inosik question is: how to make it work in fake - manually is no option ;-)

**Comment by inosik** [comment]
@forki Yes, I know.

Can you try anyways, please? Maybe we know more then and can decide what to do.

**Comment by alfonsogarciacaro** [comment]
Does it change something if you use yarn instead of npm to run the scripts in package.json? With latest fable you can do `dotnet fable yarn-run start` (equivalent to `dotnet fable npm-run start`) or the short version, `dotnet fable yarn-start`.

**Comment by inosik** [comment]
@alfonsogarciacaro It must be some output from Rollup, so using Yarn won't help here. I tried to do this:

``` shell
$ chcp.com 65001 # Sets the current code page to UTF-8, doing the same thing as FAKE does
$ dotnet fable npm-run build
```

The `build` script invokes Rollup, and running `dotnet fable ...` crashes with the same error as @forki showed above.

So the problem is actually FAKE setting the output encoding, as I wrote above. I added fsharp/FAKE#1605.

**Comment by alfonsogarciacaro** [comment]
Then maybe running Rollup in a separate shell?

**Comment by inosik** [comment]
@forki Yes, our Mono fix broke Windows :smile: See fsharp/FAKE#1461.

Linux or macOS would probably work correctly here, because their terminals default to UTF-8.

**Comment by forki** [comment]
no it doesn't do anything on windows. or where does it change it?

**Comment by inosik** [comment]
In the [`ProcessHelper` module](https://github.com/fsharp/FAKE/blob/805ca9420e0234fe2ac8fe2033f28faeec2ebb40/src/app/FakeLib/ProcessHelper.fs#L27).

**Comment by forki** [comment]
how about: https://github.com/fsharp/FAKE/pull/1606/files

**Comment by forki** [comment]
yay with latest FAKE the yarn is coming back to life!

**Comment by forki** [comment]
image

@alfonsogarciacaro  what's this?

**Comment by alfonsogarciacaro** [comment]
@forki That's a couple of warnings from Rollup, I see them also when running the command manually but they don't prevent the app from running. However, I guess because of the warnings Rollup is not returning a zero code and makes the FAKE build fail. Now we can:

1. Try to remove the warnings: it may be possible for the "Buffer" one, which is just called for the [encoding trick](https://github.com/fable-compiler/fable-react-native/blob/8f687c65fa12706e911c07d867a49a1e7d8f41b6/Fable.Helpers.ReactNative.fs#L1693-L1698), however I think it'll be difficult for the "Linking" one as this seem to come from react-native. Or:
2. Try to identify the Rollup exit codes for warnings and errors and ignore it if it's only warnings.

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm having a look at Rollup code, and apparently [they don't use a non-zero exit code for warnings](https://github.com/rollup/rollup/blob/1b0823ab8081b975cb80b7302e9f79b316774f2d/bin/src/logging.js#L33-L40). Is the build error coming from Rollup? Can you show the whole stack trace?

**Comment by forki** [comment]
yeah would be weird to exit with non-0 for warnings

**Comment by forki** [comment]
image

there is nothing interesting in the output

**Comment by inosik** [comment]
It looks like Rollup prints warnings to stderr by default, because doing `rollup -c > rollup.log` still prints the warning to the console. You can override the warning function in `rollup.config.js` with this:

``` js
export default {
  // ...
  onwarn: function(msg) {
    console.log(msg);
  }
};
```

Does printing to stderr make FAKE fail?

**Comment by forki** [comment]
it's not fake that fails - it's fable quitting with exit <> 0

@inosik can you please send a PR to my fork?

**Comment by inosik** [comment]
See #21.

**Comment by forki** [comment]
doesn't help ;-(

**Comment by inosik** [comment]
Does running `node_modules/.bin/react-native` work for you? I'm getting this error:

``` shell
$ ./node_modules/.bin/react-native run-android
Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
```

This check fails because we're on Windows and our paths have backslashes:

``` js
var installedGlobally = script.indexOf('node_modules/.bin/react-native') === -1;
```

and because the `script` value doesn't contain the `.bin/` part:

```
D:\projects\fable-react_native-demo\node_modules\react-native\local-cli\wrong-react-native.js
```

**Comment by forki** [comment]
`./node_modules/.bin/react-native run-android` doesn't work
`.\node_modules\.bin\react-native run-android` doesn't work

`react-native.cmd run-android` does work a bit further:

     A problem occurred configuring project ':react-native-onesignal'.

which is probably a real error

**Comment by alfonsogarciacaro** [comment]
For the record, in my tests I was using the `react-native` command installed globally (by running `npm i -g react-native-cli`) as this is what the React Native tutorial recommends.

**Comment by forki** [comment]
crazy! I got it working. Only one issue: Fable doesn't go to watch mode. Ideas?

**Comment by inosik** [comment]
Call `dotnet fable npm-run start` instead of `... build` from FAKE?

**Comment by forki** [comment]
ok that works. Fable is in watch mode and runs on device.

two remaining issue: 

a) ionide is unhappy and show lots of errors /cc @Krzysztof-Cieslak 
b) for normal build we need to set production flag for compiler directive

**Comment by inosik** [comment]
You can revert 94fffb5.

**Comment by enricosada** [comment]
@forki atm ionide and fsac and sdk are solid :D

`dotnt build`

```
       "e:\github\fable-react_native-demo\Nightwatch.fsproj" (Build target) (1) ->
       (CoreCompile target) ->
         C:\dotnetcli\dotnet-dev-win-x64.1.0.4\sdk\1.0.4\Sdks\FSharp.NET.Sdk\Sdk\Sdk.targets(27,5): warning : The 'CoreCompile' target should be overriden in 'FSharp.NET.Sdk' package. Maybe you need to add 'FSharp.NET.Sdk' package to fsproj or run restore [e:\github\fable-react_native-demo\Nightwatch.fsproj]
```

after adding `<PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" />` works

restorerequired4

gif is wip of new restore if not already + progress indicators for that

**Comment by forki** [comment]
ok ionide fixed with help of @enricosada and @Krzysztof-Cieslak

**Comment by forki** [comment]
so last thing on the list: compiler directives

**Comment by forki** [comment]
ok compiler directives work as well. yay!

one last thing: 

    let result =
        ExecProcess (fun info ->
            info.FileName <- dotnetExePath
            info.WorkingDirectory <- srcDir
            info.Arguments <- " fable npm-run build") TimeSpan.MaxValue
    if result <> 0 then failwith "fable shut down."

it seems that a compiler error doesn't make this quit with exit code <> 0 - therefor build continues.

@alfonsogarciacaro ideas?

**Comment by alfonsogarciacaro** [comment]
This is tricky. Before Fable 1.0, compilation would stop after encountering the first error. I changed this so you could get multiple errors and show them in the IDE ([see here](https://github.com/ionide/ionide-vscode-fsharp/issues/412#issuecomment-308996108)). For bundler it's also important not to stop compilation, because then file dependencies won't be listed and thus won't be watched for changes either.

I think this is working fine with Webpack, but Rollup had a problem because errors would stop compilation so I had to [report everything as a warning](https://github.com/fable-compiler/Fable/blob/ffbfc2cd66b99839595b98bf0151e6443d63ba3c/src/typescript/rollup-plugin-fable/index.js#L75-L77).

Probably we can work around this by adding a `failOnError` option or similar to the Rollup plugin to throw actual errors if it's not a watch compilation, what do you think?

**Comment by forki** [comment]
yes I only need to let it fail on "normal" build withoutt watch, But we need to make it so otherwise CI would just go on and create corrupt apk

**Comment by alfonsogarciacaro** [comment]
I've publish rollup-plugin-fable 1.0.6, can you please update and change [this line](https://github.com/fable-compiler/fable-react_native-demo/blob/181dc6bfdff57201718709390687de009afb37f7/rollup.config.js#L13) as follows?

```js
  plugins: [fable({extra: { failOnError: true })],
```

**Comment by forki** [comment]
how can I update to rollup-plugin-fable 1.0.6,?

**Comment by forki** [comment]
seems to work! thx

**Comment by forki** [comment]
g0w4e

wow Fable 1 is now working on my device as expected!!!!

Thanks so much everyone

**Pull request merged**
