### PR TITLE
Update ReactNative to 0.45.1

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
I tried to update to RN 0.45.1 but somehow now fable doesn't produce javascript js files anymore. Can someone see what I fucked up?

**Comment by alfonsogarciacaro** [comment]
Not sure, but it may be the .babelrc interfering with the default options for Fable. Can you try removing i? I think you don't need the react-native preset, but in case you want to add it you can do it directly in the rollup.config.js as in [here](https://github.com/fable-compiler/Fable/blob/51ed85132225491a2fe472051db98b08b4301c54/src/dotnet/Fable.Client.Browser/testapp/rollup.config.js#L8-L15).

**Comment by forki** [comment]
@alfonsogarciacaro that did not change anything. ;-(

**Comment by alfonsogarciacaro** [comment]
Hmm, I'll try to have a look

**Comment by alfonsogarciacaro** [comment]
I just had to make a couple of changes to make the build script work on macOS (see #25) but after running `sh build.sh`, the `out/Nigthwatch.js` file was generated and I could start the app with `react-native run-android` without problems.

**Comment by forki** [comment]
AWESOME: WORKS!

**Pull request merged**
